package org.javalabs.jpa.query;

import org.javalabs.jpa.query.OneToManyBinder;
import org.javalabs.jpa.descriptor.PersistenceHandler;
import org.javalabs.jpa.descriptor.RelAttribute;
import org.javalabs.jpa.model.Department;
import org.javalabs.jpa.model.User;
import jakarta.persistence.CascadeType;
import jakarta.persistence.EnumType;
import jakarta.persistence.FetchType;
import jakarta.persistence.GenerationType;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

public class OneToManyBinderTest {

    @Test
    public void testOneToManyBinder() {
        OneToManyBinder oneToMany = new OneToManyBinder(RelAttribute.RelType.ManyToOne);
        Department dep = new Department();
        User user = new User();

        user.setId(1);
        user.setDepName("HR");
        user.setFirstName("Anu");
        user.setLastName("Charles");

        dep.setDepId(1);
        dep.setDepartmentName("HR");

        List<User> userList = new ArrayList<>();
        userList.add(user);
        dep.setUser(userList);
        user.setDepartment(dep);


        List<Object> parents = new ArrayList<>();
        parents.add(dep);
        RelAttribute rel = new RelAttribute() {
            @Override
            public Relation relation() {
                return new Relation() {
                    @Override
                    public RelType relType() {
                        return RelType.ManyToOne;
                    }

                    @Override
                    public CascadeType[] cascade() {
                        return new CascadeType[0];
                    }

                    @Override
                    public FetchType fetch() {
                        return FetchType.EAGER;
                    }

                    @Override
                    public String mappedBy() {
                        return "department";
                    }
                };
            }

            @Override
            public List<Join> joins() {
                return null;
            }

            @Override
            public JoinType joinType() {
                return JoinType.LEFT_OUTER;
            }

            @Override
            public String name() {
                return "NameOfRelAttribute";
            }

            @Override
            public Class<?> datatype() {
                return null;
            }

            @Override
            public String column() {
                return null;
            }

            @Override
            public boolean isId() {
                return false;
            }

            @Override
            public boolean isAutoGenerated() {
                return false;
            }

            @Override
            public GenerationType generationType() {
                return null;
            }

            @Override
            public boolean updatable() {
                return false;
            }

            @Override
            public boolean nullable() {
                return false;
            }

            @Override
            public int length() {
                return 0;
            }

            @Override
            public boolean isVersion() {
                return false;
            }

            @Override
            public boolean isTransient() {
                return false;
            }

            @Override
            public boolean isEnum() {
                return false;
            }

            @Override
            public EnumType enumType() {
                return null;
            }
        };

        List<Object> children = new ArrayList<>();
        children.add(user);
        PersistenceHandler persist = PersistenceHandler.get();
        persist.createDescriptor(Department.class);
        persist.createDescriptor(User.class);
        oneToMany.bind(parents, rel, children);
    }
}
