package org.javalabs.jpa.query;

import org.javalabs.jpa.query.OneToOneBinder;
import org.javalabs.jpa.descriptor.PersistenceHandler;
import org.javalabs.jpa.descriptor.RelAttribute;
import org.javalabs.jpa.model.Department;
import org.javalabs.jpa.model.User;
import jakarta.persistence.CascadeType;
import jakarta.persistence.EnumType;
import jakarta.persistence.FetchType;
import jakarta.persistence.GenerationType;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

public class OneToOneBinderTest {

    @Test
    public void testOneToOneBinder() {
        OneToOneBinder oneToOneBinder = new OneToOneBinder(RelAttribute.RelType.OneToOne);

        List<Object> parents = new ArrayList<>();
        User user = new User();
        parents.add(user);
        RelAttribute rel = new RelAttribute() {
            @Override
            public Relation relation() {
                return new Relation() {
                    @Override
                    public RelType relType() {
                        return RelType.OneToMany;
                    }

                    @Override
                    public CascadeType[] cascade() {
                        return new CascadeType[0];
                    }

                    @Override
                    public FetchType fetch() {
                        return FetchType.EAGER;
                    }

                    @Override
                    public String mappedBy() {
                        return null;
                    }
                };
            }

            @Override
            public List<Join> joins() {
                return null;
            }

            @Override
            public JoinType joinType() {
                return JoinType.LEFT_OUTER;
            }

            @Override
            public String name() {
                return "NameOfRelAttribute";
            }

            @Override
            public Class<?> datatype() {
                return null;
            }

            @Override
            public String column() {
                return null;
            }

            @Override
            public boolean isId() {
                return false;
            }

            @Override
            public boolean isAutoGenerated() {
                return false;
            }

            @Override
            public GenerationType generationType() {
                return null;
            }

            @Override
            public boolean updatable() {
                return false;
            }

            @Override
            public boolean nullable() {
                return false;
            }

            @Override
            public int length() {
                return 0;
            }

            @Override
            public boolean isVersion() {
                return false;
            }

            @Override
            public boolean isTransient() {
                return false;
            }

            @Override
            public boolean isEnum() {
                return false;
            }

            @Override
            public EnumType enumType() {
                return null;
            }

            @Override
            public String check() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        };

        List<Object> children = new ArrayList<>();
        Department dep = new Department();
        children.add(dep);
        PersistenceHandler persist = PersistenceHandler.get();
        persist.createDescriptor(User.class);
        persist.createDescriptor(Department.class);
        oneToOneBinder.bind(parents,rel,children);
    }
}
