package org.javalabs.jpa.dialect;

import org.javalabs.jpa.descriptor.ClassDescriptor;
import org.javalabs.jpa.descriptor.EntityAttribute;
import org.javalabs.jpa.descriptor.RelAttribute;
import org.javalabs.jpa.descriptor.RelAttribute.Join;
import jakarta.persistence.EnumType;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Index;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author schan280
 */
public abstract class AbstractDBDialect implements SQLDialect {

    @Override
    public String create_table(ClassDescriptor desc) {
        // Extract the longest column length and data type length (needed for pretty printing).
        List<String> columneNames = new ArrayList<>(desc.attributeCount());
        List<String> columneDataTypes = new ArrayList<>(desc.attributeCount());
        List<String> columneNotNull = new ArrayList<>(desc.attributeCount());
        
        String dataType = "";
        
        for (Iterator<EntityAttribute> itr = desc.attributes(); itr.hasNext(); ) {
            EntityAttribute attribute = itr.next();
            if (! attribute.isTransient()) {
                columneNames.add(attribute.column());
                
                if (attribute.isAutoGenerated() && GenerationType.IDENTITY == attribute.generationType()) {
                    columneDataTypes.add(auto_gen_data_type());
                }
                else if (attribute.datatype().isEnum()) {
                    if (attribute.enumType() == EnumType.STRING) {
                        dataType = data_type(String.class);
                        columneDataTypes.add(dataType + "(" + attribute.length() + ")");
                    }
                    else {
                        dataType = data_type(Byte.class);
                        columneDataTypes.add(dataType);
                    }
                }
                else if (attribute.datatype() == String.class) {
                    dataType = data_type(String.class);
                    columneDataTypes.add(dataType + "(" + attribute.length() + ")");
                }
                else {
                    dataType = data_type(attribute.datatype());
                    columneDataTypes.add(dataType);
                }
                columneNotNull.add(! attribute.nullable() || attribute.isId() ? "NOT NULL" : "");
            }
        }
        
        int colLength = 0;
        int dtypeLength = 0;
        
        for (int i = 0; i < columneNames.size(); i ++) {
            String name = columneNames.get(i);
            if (name.length() > colLength) {
                colLength = name.length();
            }
        }
        for (int i = 0; i < columneDataTypes.size(); i ++) {
            String dtype = columneDataTypes.get(i);
            if (dtype.length() > dtypeLength) {
                dtypeLength = dtype.length();
                if (dtypeLength > 18) {
                    dtypeLength = 18;
                }
            }
        }
        
        colLength += 2;
        dtypeLength += 2;
        
        // Now, start forming the query.
        StringBuilder script = new StringBuilder(128);
        script.append("CREATE TABLE ").append(desc.table()).append(" (");
        
        int cDiff = 0;
        int dDiff = 0;
        
        for (int i = 0; i < columneNames.size(); i ++) {
            // Add column name
            script.append("\n    ").append(columneNames.get(i));
            
            // Formatting 1 ...
            cDiff = colLength - columneNames.get(i).length();
            for (int j = 0; j < cDiff; j ++) {
                script.append(" ");
            }
            
            // Add data type
            script.append(columneDataTypes.get(i));

            // Formatting 2 ...
            dDiff = dtypeLength - columneDataTypes.get(i).length();
            for (int j = 0; j < dDiff; j ++) {
                script.append(" ");
            }
            
            // Add null or not null clause
            script.append(columneNotNull.get(i));

            if (i < columneNames.size() - 1) {
                script.append(",");
            }
        }
        script.append("\n)").append(";");
        
        return script.toString();
    }

    @Override
    public String drop_table(ClassDescriptor desc) {
        return "DROP TABLE " + desc.table() + ";";
    }

    @Override
    public String primary_key(ClassDescriptor desc) {
        StringBuilder script = new StringBuilder(32);
        script.append("ALTER TABLE ").append(desc.table())
                .append("\n").append("ADD CONSTRAINT ").append(desc.table()).append("_pk")
                .append("\n").append("PRIMARY KEY (");
        
        for (Iterator<EntityAttribute> itr = desc.ids(); itr.hasNext(); ) {
            EntityAttribute attribute = itr.next();
            script.append(attribute.column());
            
            if (itr.hasNext()) {
                script.append(", ");
            }
        }
        script.append(")").append(";");
        
        return script.toString();
    }

    @Override
    public String index(ClassDescriptor desc) {
        Index[] indexes = desc.indexes();
        if (indexes == null || indexes.length == 0) {
            return "";
        }
        StringBuilder script = new StringBuilder(32);
        
        for (int i = 0; i < indexes.length; i ++) {
            script.append("CREATE ").append(indexes[i].unique() ? "UNIQUE " : "").append("INDEX ")
                    .append(indexes[i].name() != null
                            && indexes[i].name().length() > 0
                            ? indexes[i].name()
                            : desc.table() + (indexes[i].unique() ? "_uk" : "_ik"))
                    .append(indexes[i].name() != null
                            && indexes[i].name().length() > 0
                            ? "" : (indexes.length > 1 ? i : ""))
                    .append("\n").append("ON ").append(desc.table()).append(" (").append(indexes[i].columnList()).append(")")
                    .append(";");
            
            if (i < indexes.length - 1) {
                script.append("\n\n");
            }
        }
        return script.toString();
    }

    @Override
    public String foreign_key(ClassDescriptor desc) {
        List<RelAttribute> rels = new ArrayList<>(4);
        
        if (desc.manyToOne() != null) {
            rels.addAll(desc.manyToOne());
        }
        if (desc.oneToOne() != null) {
            rels.addAll(desc.oneToOne());
        }
        
        StringBuilder script = new StringBuilder(128);
        boolean isFk = true;
        for (int i = 0; i < rels.size(); i ++) {
            RelAttribute rel = rels.get(i);
            
            for (int j = 0; j < rel.joins().size(); j ++) {
                Join join = rel.joins().get(j);
                if (! join.fk()) {
                    isFk = false;
                    break;
                }
            }
            if (rel.joins().isEmpty() || ! isFk) {
                continue;
            }
            
            script.append("ALTER TABLE ").append(desc.table())
                .append("\n").append("ADD CONSTRAINT ").append(desc.table()).append("_fk")
                .append("\n").append("FOREIGN KEY (");

            for (int j = 0; j < rel.joins().size(); j ++) {
                Join join = rel.joins().get(j);
                script.append(join.joinColumn());
                if (j < rel.joins().size() - 1) {
                    script.append(", ");
                }
            }
            script.append(")").append("\n");
            script.append("REFERENCES ").append(rel.joins().get(0).joinTable()).append(" (");
            
            for (int j = 0; j < rel.joins().size(); j ++) {
                Join join = rel.joins().get(j);
                script.append(join.referencedColumn());
                if (j < rel.joins().size() - 1) {
                    script.append(", ");
                }
            }
            script.append(")").append(";");
            
            if (i < rels.size() - 1) {
                script.append("\n\n");
            }
        }
        return script.toString();
    }
    
    protected abstract String auto_gen_data_type();
}
