#!/bin/sh

# Example: sh model-gen -j $HOME/temp/folks-app -k io.opns.app -d postgres -h localhost -p 5432 -n ecmdb -s public -u test -w p\@\$\$word -x fks_

export BASE_DIR=$HOME/Projects/jpa-lite

export CLASSPATH=$BASE_DIR/target/jpa-lite-1.0.1.jar
export CLASSPATH=$CLASSPATH:$BASE_DIR/lib/jakarta.persistence-api-4.0.0-M1.jar
export CLASSPATH=$CLASSPATH:$BASE_DIR/lib/slf4j-api-2.1.0-alpha1.jar
export CLASSPATH=$CLASSPATH:$BASE_DIR/lib/slf4j-simple-2.1.0-alpha1.jar
export CLASSPATH=$CLASSPATH:$BASE_DIR/lib/postgresql-42.7.5.jar
export CLASSPATH=$CLASSPATH:$HOME/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/4.0.2/jakarta.xml.bind-api-4.0.2.jar
export CLASSPATH=$CLASSPATH:$HOME/.m2/repository/org/glassfish/jaxb/jaxb-runtime/4.0.5/jaxb-runtime-4.0.5.jar
export CLASSPATH=$CLASSPATH:$HOME/.m2/repository/org/glassfish/jaxb/jaxb-core/4.0.5/jaxb-core-4.0.5.jar
export CLASSPATH=$CLASSPATH:$HOME/.m2/repository/com/sun/istack/istack-commons-runtime/4.1.2/istack-commons-runtime-4.1.2.jar
export CLASSPATH=$CLASSPATH:$HOME/.m2/repository/jakarta/activation/jakarta.activation-api/2.1.3/jakarta.activation-api-2.1.3.jar

export CLASSPATH=$CLASSPATH:$HOME/.m2/repository/org/javalabs/decl/decl-class-gen/2.0.1/decl-class-gen-2.0.1.jar
export CLASSPATH=$CLASSPATH:$HOME/.m2/repository/org/javalabs/decl/decl-util/2.0.1/decl-util-2.0.1.jar

export DEBUG_OPT="-Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9792"
export JAVA_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=TRACE"

#java -classpath $CLASSPATH org.javalabs.jpa.entity.EntityGenerator "$@"
java -Dpause $DEBUG_OPT $JAVA_OPTS -classpath $CLASSPATH org.javalabs.jpa.entity.EntityGenerator "$@"
