package org.javalabs.jpa.descriptor;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;

/**
 * Interface to represent the metadata of an entity attribute.
 * 
 * <p>
 * An attribute of a jpa entity can have multiple properties. For example, it can
 * be a primary key, or it can be a versionable column, or it can be an enum, or
 * it can be a transient property, etc. All these metadata information is captured
 * in this class.
 *
 * @author Sudiptasish Chanda
 */
public interface EntityAttribute {
    
    /**
     * Return the name of the entity attribute.
     * @return String
     */
    String name();
    
    /**
     * Return the java type of the attribute.
     * @return Class
     */
    Class<?> datatype();
    
    /**
     * Return the name of the table column this attribute is associated with.
     * The attribute will be annotated with {@link Column} to represent the underlying
     * table column it is associated to. If no such annotation is present and the
     * attribute/field is not marked as {@link Transient}, then the name of the
     * field will be treated as the column name.
     * 
     * @return String
     */
    String column();
    
    /**
     * Indicates whether this attribute is an id column.
     * An attribute will be an id column, if it has the annotation {@link Id}.
     * 
     * @return boolean
     */
    boolean isId();
    
    /**
     * Indicate whether the value of the id attribute(s) will be auto generated
     * by the database provider.
     * 
     * @return boolean
     */
    boolean isAutoGenerated();
    
    /**
     * Return the auto generated type.
     * 
     * @return GenerationType
     */
    GenerationType generationType();
    
    /**
     * Verify if this column is updatable.
     * Any updatable column would be skipped during a database update operation.
     * 
     * @return boolean
     */
    boolean updatable();
    
    /**
     * Verify if this column is nullable.
     * @return boolean
     */
    boolean nullable();
    
    /**
     * Return the check constraint of this column.
     * @return String
     */
    String check();
    
    /**
     * Return the column length.
     * @return int
     */
    int length();
    
    /**
     * Indicates whether this attribute is an versionable column.
     * An attribute will be an id column, if it has the annotation {@link Version}.
     * A version column is primarily a numeric column, where it will be auto-incremented
     * every time the entry changes. It will be injected automatically by the
     * framework.
     * 
     * @return boolean
     */
    boolean isVersion();
    
    /**
     * Indicates whether this entity attribute is of transient type.
     * A {@link Transient} attribute will never be persisted. Hence while generating
     * the insert query, this attribute will be skipped.
     * 
     * @return boolean
     */
    boolean isTransient();
    
    /**
     * Indicate if the attribute is an Enum type.
     * JPA LiTE supports handling enum data type. A java enum type will be translated
     * either into a {@link String} or an {@link Integer} depending on the option
     * chosen while modelling the {@link Entity} class.
     * 
     * @return boolean
     */
    boolean isEnum();
    
    /**
     * Return the enumerated type.
     * @return EnumType
     */
    EnumType enumType();
}