package org.javalabs.jpa.descriptor;

import jakarta.persistence.CheckConstraint;
import jakarta.persistence.Column;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;
import java.lang.reflect.Field;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.WildcardType;
import java.util.Collection;

/**
 * Platform provided implementation of {@link EntityAttribute} class.
 *
 * @author Sudiptasish Chanda
 */
public class EntityAttributeImpl implements EntityAttribute {
    
    private final String name;
    private final Class<?> datatype;
    
    private String column;
    private boolean id = false;
    private boolean generated = false;  // Generated id column will be excluded in insert statement
    private GenerationType genType = GenerationType.AUTO;
    private boolean updatable = true;
    private boolean nullable = true;
    private String check;
    private int length = -1;
    private boolean trans = false;
    private boolean enumerated = false;
    private boolean verionable = false;
    private EnumType enumType = null;
    
    EntityAttributeImpl(Field field) {
        name = field.getName();
        
        if (field.getType() == byte[].class) {      // Special handling for byte array ...
            datatype = byte[].class;
        }
        else if (field.getType().isArray()) {
            datatype = field.getType().getComponentType();
        }
        else if (Collection.class.isAssignableFrom(field.getType())) {
            ParameterizedType pType = (ParameterizedType) field.getGenericType();
            if (pType.getActualTypeArguments()[0] instanceof WildcardType) {
                datatype = WildcardType.class;
            }
            else {
                datatype = (Class<?>) pType.getActualTypeArguments()[0];
            }
        }
        else {
            datatype = field.getType();
        }
        column = name;
        
        init(field);
    }

    private void init(Field field) {
        id = field.isAnnotationPresent(Id.class);
        if (id) {
            updatable = false;
        }
        
        GeneratedValue gn = field.getAnnotation(GeneratedValue.class);
        if (gn != null) {
            generated = true;
            if (gn.strategy() != null) {
                genType = gn.strategy();
            }
        }
        trans = field.isAnnotationPresent(Transient.class);
        verionable = field.isAnnotationPresent(Version.class);
        
        Column colAnnotation = field.getAnnotation(Column.class);
        if (colAnnotation != null) {
            column = colAnnotation.name().toLowerCase();
            updatable = colAnnotation.updatable();
            nullable = colAnnotation.nullable();
            if (datatype == String.class) {
                length = colAnnotation.length();
            }
            CheckConstraint[] checks = colAnnotation.check();
            if (checks != null && checks.length > 0) {
                check = "CHECK (" + checks[0].constraint() + ")";
            }
        }
        
        if (datatype != null && datatype.isEnum()) {
            Enumerated emtdAnnotation = field.getAnnotation(Enumerated.class);
            if (emtdAnnotation != null) {
                enumerated = true;
                enumType = emtdAnnotation.value();
                
                if (enumType == EnumType.STRING) {
                    length = colAnnotation.length();
                }
            }
        }
        if (generated && ! Number.class.isAssignableFrom(datatype)) {
            throw new IllegalArgumentException("Attribute " + field.getName() + " is a Generated column."
                    + " The datatype must be a Number");
        }
    }

    @Override
    public final String name() {
        return name;
    }

    @Override
    public final Class<?> datatype() {
        return datatype;
    }

    @Override
    public final String column() {
        return column;
    }

    @Override
    public final boolean isId() {
        return id;
    }

    @Override
    public boolean isAutoGenerated() {
        return generated;
    }

    @Override
    public GenerationType generationType() {
        return genType;
    }

    @Override
    public final boolean isVersion() {
        return verionable;
    }

    @Override
    public final boolean isEnum() {
        return enumerated;
    }

    @Override
    public final EnumType enumType() {
        return enumType;
    }

    @Override
    public final boolean isTransient() {
        return trans;
    }

    @Override
    public boolean updatable() {
        return updatable;
    }

    @Override
    public boolean nullable() {
        return nullable;
    }

    @Override
    public String check() {
        return check;
    }

    @Override
    public int length() {
        return length;
    }
}
