package org.javalabs.jpa.query;

import org.javalabs.jpa.LiteEntityManager;
import org.javalabs.jpa.descriptor.ClassDescriptor;
import org.javalabs.jpa.descriptor.EntityAttribute;
import jakarta.persistence.EntityManager;
import jakarta.persistence.GenerationType;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * Insert query that will handle all insert operation.
 * 
 * <p>
 * A call to {@link EntityManager#persist(java.lang.Object) } will call this query
 * object to persist the record. {@link InsertQuery} class internally maintains a
 * cache to hold the in-transit entities, i.e., the one to be persisted. Once the cache is full,
 * or user has explicitly issued a {@link EntityManager#flush() }, the in-memory
 * record(s) will be persisted in underlying database. The cache is introduced in
 * order to reduce the number of DB calls, thus improving the overall performance
 * of the system.
 * 
 * <p>
 * Instance of this class is not threadsafe. The standard practice is, one {@link EntityManager}
 * will always have a single instance of {@link InsertQuery}.
 *
 * @author Sudiptasish Chanda
 */
public class InsertQuery extends WriteQuery {
    
    public InsertQuery(LiteEntityManager em) {
        super(em);
    }

    @Override
    protected String dbQuery() {
        return builder().insertQuery(entityClass());
    }
    
    @Override
    protected PreparedStatement statemnt(Connection conn, String query) throws SQLException {
        String[] columns = null;
        int i = 0;
        
        ClassDescriptor desc = handler().getDescriptor(entityClass());
        
        for (Iterator<EntityAttribute> itr = desc.ids(); itr.hasNext(); ) {
            EntityAttribute attribute = itr.next();
            
            // Only for IDENTITY and Number data type
            if (attribute.isAutoGenerated() && GenerationType.IDENTITY == attribute.generationType()
                    && Number.class.isAssignableFrom(attribute.datatype())) {
                
                if (columns == null) {
                    columns = new String[desc.idCount()];
                }
                columns[i] = attribute.column();
                i ++;
            }
        }
        if (columns != null && columns.length == desc.idCount()) {
            // return conn.prepareStatement(query, columns);
            return conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
        }
        else {
            return conn.prepareStatement(query);
        }
    }
    
    @Override
    protected void retrieveGeneratedId(PreparedStatement pstmt) throws SQLException {
        ClassDescriptor desc = handler().getDescriptor(entityClass());
        boolean keyRequested = false;
        
        Object entity = null;
        int i = 0;
        
        for (Iterator<EntityAttribute> itr = desc.ids(); itr.hasNext(); ) {
            EntityAttribute attribute = itr.next();
            
            // Only for IDENTITY and Number data type
            if (attribute.isAutoGenerated() && GenerationType.IDENTITY == attribute.generationType()
                    && Number.class.isAssignableFrom(attribute.datatype())) {
                
                keyRequested = true;
                break;
            }
        }
        
        if (keyRequested) {
            try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                while (generatedKeys.next()) {
                    int j = 1;
                    for (Iterator<EntityAttribute> itr = desc.ids(); itr.hasNext(); j ++) {
                        EntityAttribute attribute = itr.next();
                        entity = entities.get(i);

                        if (attribute.datatype() == Long.class) {
                            handler().set(entity, attribute.column(), generatedKeys.getLong(j));
                        }
                        else if (attribute.datatype() == Integer.class) {
                            handler().set(entity, attribute.column(), generatedKeys.getInt(j));
                        }
                        else if (attribute.datatype() == Short.class) {
                            handler().set(entity, attribute.column(), generatedKeys.getShort(j));
                        }
                        else if (attribute.datatype() == Double.class) {
                            handler().set(entity, attribute.column(), generatedKeys.getDouble(j));
                        }
                        else if (attribute.datatype() == Float.class) {
                            handler().set(entity, attribute.column(), generatedKeys.getFloat(j));
                        }
                    }
                    i ++;
                }
            }
        }
    }

    @Override
    protected List<List<Object>> prepare(PreparedStatement pStmt) throws SQLException {
        List<List<Object>> params = new ArrayList<>(recordCount());
        List<Object> binds = null;
        Object bind = null;
        int index = 0;
        
        ClassDescriptor desc = handler().getDescriptor(entityClass());
        
        for (Object entity : entities) {
            index = 0;
            
            if (verbose()) {
                binds = new ArrayList<>(desc.attributeCount());
            }
            for (Iterator<EntityAttribute> itr = desc.attributes(); itr.hasNext(); ) {
                EntityAttribute attribute = itr.next();
                if (!attribute.isTransient() && !attribute.isAutoGenerated()) {
                    bind = handler().get(entity, attribute.column());
                    queryMechansim().prepare(pStmt, ++ index, attribute, bind);

                    if (verbose()) {
                        binds.add(bind);
                    }
                }
            }            
            // Framework always facilitates batching.
            pStmt.addBatch();
            
            if (verbose()) {
                params.add(binds);
            }
        }
        return params;
    }
}
